table Dim_Product
	lineageTag: 99d9c625-d520-4bb4-8450-9c46889d0489

	column category
		dataType: string
		lineageTag: fcbbd439-ec3d-4eca-96be-f66961f5c038
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: ab5cd800-0b4a-4889-8edb-c4099e7b43ee
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: 58c70a8d-87c6-4cf1-be9e-f6161ead088b
		summarizeBy: none
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	partition Dim_Product = m
		mode: import
		source =
				let
				    Source = Fact_Sales,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"sale_id", "date", "city", "store_format", "quantity", "sales_amount"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns", {"item"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

