table Fact_Sales
	lineageTag: d26001fd-8f65-410a-b107-8c38a6932f9b

	measure 'Total Sales' = SUM(Fact_Sales[sales_amount])
		lineageTag: a5e64cb4-5145-4e39-9d65-f3b3c4f721f7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Previous Month Sales' = CALCULATE([Total Sales],DATEADD(Dim_Date[date],-1,MONTH))
		lineageTag: 9a5f5720-2c2e-4c50-8591-e5d13a1fd811

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM Growth %' = DIVIDE([Total Sales] - [Previous Month Sales], [Previous Month Sales])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: fdd240ed-d904-436b-9576-170b4a723a58

	measure 'Running Total Sales' = CALCULATE([Total Sales],FILTER(ALLSELECTED(Dim_Date[date]),Dim_Date[date]<=MAX(Dim_Date[date])))
		lineageTag: 05488924-5a4b-42ac-a4ac-984c1da82cd5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Product Sales Rank' = RANKX(ALLSELECTED(Dim_Product[item]),[Total Sales],,DESC,Dense)
		formatString: 0
		lineageTag: 7c0109e2-9fd8-4e48-bca7-6de4dcb19b38

	measure 'Average Transaction Value' = DIVIDE([Total Sales],DISTINCTCOUNT(Fact_Sales[sale_id]))
		lineageTag: 2bcf96eb-df7d-4494-bee4-4393f88fc16d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: 06fe674b-c318-4b54-81a9-488a361204c6
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7d6f4606-ebd7-4134-a02f-a13c76f770ce
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: ef0548e9-26ea-4094-9479-c53db02827e7
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: 74b39e95-dc2c-40a3-b20f-68b5ec838679
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: ac7e10c2-a84b-45a0-adf7-c76716c05252
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: b7d84f90-e339-473e-a622-54182957b7c4
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 20b17330-8bcf-476c-8bf6-53e1652036f9
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: 952c00ff-d22b-4923-9bcb-a3032bc580a8
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: 12a98500-aa60-4901-9400-c53ab9a3e454
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\vboxuser\Documents\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

